### PR TITLE
Refactored Limitized_Garage_Generator_v1.1.py & Updated README

### PR DESCRIPTION
**Pull request by ryan-harrington**
## Changes
* [`Limitized_Garage_Generator_v1.1.py`](https://github.com/Limitized/garageGenerator/blob/master/Limitized_Garage_Generator_v1.1.py) has been refactored.
* [`README.md`](https://github.com/Limitized/garageGenerator/blob/master/README.md) has been updated/cleaned up.

### CODE REVIEW

**Comment by ghost** [comment]
<p>Wow, the refactored python file looks <em>much</em> better, in addition to the updated README.md file!<p>

**Comment by ryan-harrington** [comment]
@Limitized Does the refactored code style look okay?

**Comment by mouncg** [comment]
lmao, i can take a look @Le-SirH

**Review by mouncg — APPROVED** [review]
good changes, seems like black code formatter ngl LMAO

**Comment by ryan-harrington** [comment]
What is that?

**Comment by ryan-harrington** [comment]
How is the status with this PR?

**Pull request closed without merging**
